
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Astronomy'
tagline:          'from http://cnx.org/contents/2e737be8-ea65-48c3-aa0a-9f35b4c6a966@14.4 (CC-BY)'
url:              https://github.com/philschatz/astronomy-book
origin:           http://cnx.org/contents/2e737be8-ea65-48c3-aa0a-9f35b4c6a966@14.4

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          14.4

bookviewer:       https://philschatz.com/book-viewer

